repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-metatex_logo_light.png
    - docs/images/nf-core-metatex_logo_light.png
    - docs/images/nf-core-metatex_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-metatex_logo_light.png
    - docs/images/nf-core-metatex_logo_light.png
    - docs/images/nf-core-metatex_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: lexanomics
  name: metatex
  description: A concise metagenomics pipeline for assembly and taxonomics profiling
  author: Diego Texeira, Iara Souza and Andre Fonseca
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - adaptivecard
  is_nfcore: false
